language: swift
os: osx
osx_image: xcode10.2

cache: bundler

## Create a build matrix to execute against multiple simulators/iOS versions.
## Script stage uses `xcrun simctl list devices`, filtered by DEVICE_GREP and SYSTEM, to find device UDIDs.
## ISO_DEVICE is human-readable summary.
env:
 - DEVICE_GREP="SE", IOS_VERSION="11-4", IOS_DEVICE="iPhone SE (11.4)"
 - DEVICE_GREP="SE", IOS_VERSION="12-2", IOS_DEVICE="iPhone SE (12.2)"

addons:
  homebrew:
    packages:
    - jq

before_install:
  - rvm install default
  - gem install bundler
  - gem install slather
  - gem install cocoapods

script:
  - udid=`xcrun simctl list devices --json | jq --raw-output '.devices | to_entries | map(select(.key | contains("'$IOS_VERSION'"))) | .[].value[] | select(.name | match("'$DEVICE_GREP'"; "i")) | .udid'`
  - echo 'Starting build and test...'
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CleanComponents.xcodeproj -scheme CleanComponents -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,id=$udid" ONLY_ACTIVE_ARCH=NO
  - osascript -e 'tell app "Simulator" to quit'

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./test-reports/cobertura.xml -X coveragepy -X gcov -X xcode || echo "Codecov did not collect coverage reports"
  - pod lib lint
