language: swift

osx_image: xcode10.2
env:
  matrix:
    - TEST_SDK=iphonesimulator11.4 OS=11.4 NAME='iPhone 7'
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone XR'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CleanComponents.xcodeproj -scheme CleanComponents -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
