language: swift
os: osx
osx_image: xcode10.2

cache: bundler

## Create a build matrix to execute against multiple simulators/iOS versions.
## UDIDs used below are from `xcrun simctl list` command in the Job log of the travis-ci.com build.
## The UDIDs are used in the script stage to determine the destination for our tests.
## ISO_DEVICE is not used in the script but is useful to know what OS version is tested.
env:
 - UDID="D94DC60A-EF32-4CA8-81C6-0746BAA0345F", IOS_DEVICE="iPhone 5s (11.4)"
 - UDID="A80EBAAF-A957-48F7-B486-4119DB167A2E", IOS_DEVICE="iPhone Xs (12.2)"

before_install:
  - rvm install default
  - gem install bundler
  - gem install slather
  - gem install cocoapods

script:
  - xcrun instruments -s devices
  - echo Starting build and test...
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CleanComponents.xcodeproj -scheme CleanComponents -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,id=$UDID" ONLY_ACTIVE_ARCH=NO
  - osascript -e 'tell app "Simulator" to quit'

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./test-reports/cobertura.xml -X coveragepy -X gcov -X xcode || echo "Codecov did not collect coverage reports"
  - pod lib lint
