//
//  ListOrdersInteractor.swift
//  CleanComponents
//
//  Created by Andy Warwick on 24/04/2019.
//  Copyright (c) 2019 Andrew Warwick. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CleanComponents

protocol ListOrdersBusinessLogic: CleanInteractor
{
  func doSomething(request: ListOrders.Something.Request)
}

protocol ListOrdersDataStore
{
  //var name: String { get set }
}

final class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: CleanPresenter
  var workers: [CleanWorker] = []

  var worker: CleanWorker? {
    return workers.isEmpty ? nil : workers.first
  }

  init(presenter: CleanPresenter) {
    self.presenter = presenter
  }

  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListOrders.Something.Request)
  {
//    worker = ListOrdersWorker()
//    worker?.doSomeWork()

//    let response = ListOrders.Something.Response()
//    presenter?.presentSomething(response: response)
  }
}
