//
//  ListOrdersInteractor.swift
//  CleanComponents
//
//  Created by Andy Warwick on 24/04/2019.
//  Copyright (c) 2019 Andrew Warwick. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CleanComponents

protocol ListOrdersBusinessLogic
{
  func doSomething(request: ListOrders.Something.Request)
}

protocol ListOrdersDataStore
{
  //var name: String { get set }
}

final class ListOrdersInteractor: CleanInteractor, ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: CleanPresenter?
  var worker: CleanWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListOrders.Something.Request)
  {
//    worker = ListOrdersWorker()
//    worker?.doSomeWork()

//    let response = ListOrders.Something.Response()
//    presenter?.presentSomething(response: response)
  }
}
